### ISSUE TITLE
Game Stats

### ISSUE THREAD

**Issue by chf2** [balloosnafoo/no-kicker#4]
I'm not sure that Game Stats needs team IDs -- the stats appear to be player specific?

**Comment by balloosnafoo** [comment]
Did you interpret those as user managed teams, because they are meant to be the real life teams. I guess they still aren't absolutely necessary, but I'll need the information if I want to let users browse stats against a particular team (e.g. a manager who has an RB against the Giants next week might want to know how previous RBs have fared). The alternative seems to be having the entire nfl's schedule in my db, which seems equally complicated.

**Comment by chf2** [comment]
Ah ok, yes I thought it was the teams in your league. That make sense that we would want that data based on the real life teams
